### ISSUE TITLE
Make namespace value configurable (Currently hard-coded to signadot)

### ISSUE THREAD

**Issue by prajain12** [signadot/charts#28]
Namespace must be configurable by the user. Right now it is hardcoded to "signadot"
As in some cases, the chart will not have the privileges to create a new namespace.

**Comment by arjun-sd** [comment]
@prajain12 Thanks for filing the issue. Would taking the namespace creation out of `helm` having admins do that separately before running helm address your concerns?

**Comment by prajain12** [comment]
> @prajain12 Thanks for filing the issue. Would taking the namespace creation out of `helm` having admins do that separately before running helm address your concerns?

Yes.
"signadot" can stay as the default namespace

**Comment by arjun-sd** [comment]
This has been addressed in the latest [v0.8.0 release](https://docs.signadot.com/docs/release-notes#2022-02-23) of the Signadot operator
